<?php
/**
 * RewardGenerateVoucherTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vouchery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchery API Reference
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Vouchery;

use PHPUnit\Framework\TestCase;

/**
 * RewardGenerateVoucherTest Class Doc Comment
 *
 * @category    Class
 * @description RewardGenerateVoucher
 * @package     Vouchery
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RewardGenerateVoucherTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RewardGenerateVoucher"
     */
    public function testRewardGenerateVoucher()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "prefix"
     */
    public function testPropertyPrefix()
    {
    }

    /**
     * Test attribute "code_type"
     */
    public function testPropertyCodeType()
    {
    }

    /**
     * Test attribute "random_part_length"
     */
    public function testPropertyRandomPartLength()
    {
    }

    /**
     * Test attribute "voucher_campaign_id"
     */
    public function testPropertyVoucherCampaignId()
    {
    }
}
