<?php
/**
 * SubCampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Vouchery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchery API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Vouchery;

use PHPUnit\Framework\TestCase;

/**
 * SubCampaignTest Class Doc Comment
 *
 * @category    Class
 * @description SubCampaign
 * @package     Vouchery
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SubCampaignTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SubCampaign"
     */
    public function testSubCampaign()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "triggers_on"
     */
    public function testPropertyTriggersOn()
    {
    }

    /**
     * Test attribute "trigger_name"
     */
    public function testPropertyTriggerName()
    {
    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "customer_information"
     */
    public function testPropertyCustomerInformation()
    {
    }

    /**
     * Test attribute "max_total_budget"
     */
    public function testPropertyMaxTotalBudget()
    {
    }

    /**
     * Test attribute "max_redemptions"
     */
    public function testPropertyMaxRedemptions()
    {
    }

    /**
     * Test attribute "minimum_value"
     */
    public function testPropertyMinimumValue()
    {
    }

    /**
     * Test attribute "max_discount"
     */
    public function testPropertyMaxDiscount()
    {
    }

    /**
     * Test attribute "redemptions_count"
     */
    public function testPropertyRedemptionsCount()
    {
    }

    /**
     * Test attribute "total_budget_spent"
     */
    public function testPropertyTotalBudgetSpent()
    {
    }

    /**
     * Test attribute "vouchers_distributed_count"
     */
    public function testPropertyVouchersDistributedCount()
    {
    }

    /**
     * Test attribute "vouchers_count"
     */
    public function testPropertyVouchersCount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "currency_symbol"
     */
    public function testPropertyCurrencySymbol()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "purpose"
     */
    public function testPropertyPurpose()
    {
    }

    /**
     * Test attribute "medium"
     */
    public function testPropertyMedium()
    {
    }

    /**
     * Test attribute "voucher_type"
     */
    public function testPropertyVoucherType()
    {
    }

    /**
     * Test attribute "voucher_max_redemptions"
     */
    public function testPropertyVoucherMaxRedemptions()
    {
    }

    /**
     * Test attribute "voucher_code_type"
     */
    public function testPropertyVoucherCodeType()
    {
    }

    /**
     * Test attribute "voucher_random_part_length"
     */
    public function testPropertyVoucherRandomPartLength()
    {
    }

    /**
     * Test attribute "voucher_prefix"
     */
    public function testPropertyVoucherPrefix()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "updated_by"
     */
    public function testPropertyUpdatedBy()
    {
    }
}
