<?php
/**
 * CategoriesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Vouchery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchery API Reference
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Vouchery;

use \Vouchery\Configuration;
use \Vouchery\ApiException;
use \Vouchery\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CategoriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Vouchery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CategoriesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCategory
     *
     * Create a category.
     *
     */
    public function testCreateCategory()
    {
    }

    /**
     * Test case for deleteCategory
     *
     * Delete a category.
     *
     */
    public function testDeleteCategory()
    {
    }

    /**
     * Test case for getCategories
     *
     * Get all categories for a campaign.
     *
     */
    public function testGetCategories()
    {
    }

    /**
     * Test case for getCategory
     *
     * Get a category.
     *
     */
    public function testGetCategory()
    {
    }

    /**
     * Test case for updateCategory
     *
     * Update a category.
     *
     */
    public function testUpdateCategory()
    {
    }
}
