<?php
/**
 * CustomersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Vouchery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchery API Reference
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Contact: hello@vouchery.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Vouchery;

use \Vouchery\Configuration;
use \Vouchery\ApiException;
use \Vouchery\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Vouchery
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for assignVouchersToCustomer
     *
     * Assign vouchers to a customer.
     *
     */
    public function testAssignVouchersToCustomer()
    {
    }

    /**
     * Test case for createCustomer
     *
     * Create a customer.
     *
     */
    public function testCreateCustomer()
    {
    }

    /**
     * Test case for deleteCustomer
     *
     * Delete a customer.
     *
     */
    public function testDeleteCustomer()
    {
    }

    /**
     * Test case for getCustomer
     *
     * Get a customer.
     *
     */
    public function testGetCustomer()
    {
    }

    /**
     * Test case for getCustomerRedemptions
     *
     * Get redemptions performed by a customer.
     *
     */
    public function testGetCustomerRedemptions()
    {
    }

    /**
     * Test case for getCustomerVouchers
     *
     * Get vouchers assigned to a customer.
     *
     */
    public function testGetCustomerVouchers()
    {
    }

    /**
     * Test case for getCustomers
     *
     * Get all customers.
     *
     */
    public function testGetCustomers()
    {
    }

    /**
     * Test case for importCustomers
     *
     * Import your own customers.
     *
     */
    public function testImportCustomers()
    {
    }

    /**
     * Test case for removeVouchersFromCustomer
     *
     * Remove (unassign) vouchers from a customer.
     *
     */
    public function testRemoveVouchersFromCustomer()
    {
    }

    /**
     * Test case for updateCustomer
     *
     * Update a customer.
     *
     */
    public function testUpdateCustomer()
    {
    }
}
